# SITE SETTINGS
title: Open science lab for biodiversity
description: We make biodiversity research open and reproducible
author: oscibio team members
url: "https://oscibio.inbo.be" # Custom domain is not set via CNAME, so url and baseurl need to be indicated
baseurl: "" # Otherwise GitHub Pages will set this to "/oscibio"

# SOCIAL PROFILES
social:
  email: oscibio@inbo.be
  twitter: oscibio
  github: inbo/oscibio
  mastodon: https://fosstodon.org/@oscibio

# THEME SETTINGS (ALL OPTIONAL)
theme: minima
remote_theme: peterdesmet/petridish
posts_on_home: 3
tweets_on_home: true
archive_permalink: /blog/
github_edit: true
colors:
  links: "#356196"  # INBO blue
  banner: "#c04384" # INBO fuchsia
  footer: "#3c3c3c" # INBO gray
rounded_corners: true

# BUILD SETTINGS
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed                         # Create RSS feed for posts
  - jekyll-sitemap                      # Create sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: posts
    values:
      permalink: "/blog/:slug/"
